# Generated by Django 4.0.1 on 2022-01-17 00:19

import core.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(max_length=500)),
                ('lv_prioridade', models.PositiveIntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta'), (4, 'Critica')])),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_final', models.DateTimeField(default=core.models.get_data_final)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('concluido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
